### PR TITLE
Fix: Theme preview window + New UI components

### LINKED ISSUE #92: Redesign all the theme-related UI components
Below I have provided screenshots of what it currently looks like, with no themes applied:
`ThemeSelector`(Pane):
Image
`ThemeDownloadPane`:
Image
`ThemeDownloadCell`:
Image
`ThemeExamplePane`:
Image

Clearly, these UI components need redoing from scratch, as visually they are extremely unappealing, with buggy styles, weird layouts, a lack of proper translation, and undesirable UX.

### PR DESCRIPTION
**Pull request by Exanc**
Fixes https://github.com/Railroad-Team/Railroad/issues/92

This PR adds few UI components, fixes the theme preview windows and also provides some small UI related fixes.

Changelog:
- `ThemeExamplePane`:
  - Translated the theme preview
  - Add the new UI components the theme preview
- `ThemeExamplePane` & `ThemeDowloadPane`:
  - Fixed the theme not applying to the preview window
- New UI components:
  - `RRCheckBox`
  - `RRRadioButton`
  - `RRToggleButton`
  - `LocalizedComboBox`
  - `RRPasswordField`
  - `RRTableView`
  - `LocalizedTableColumn`
- New CSS to go with these components

### CODE REVIEW

**Comment by Exanc** [comment]
Ready for another round of review

**Comment by Exanc** [comment]
Allright, i think we're not going to squeeze anything more from copilot

File: railroad-core/src/main/java/dev/railroadide/core/ui/RRButton.java [hunk 1]
```diff
@@ -18,51 +23,57 @@
...
-    private String originalText;
     private Node originalGraphic;
     private FontIcon loadingSpinner;
 
+    //#endregion
+
+    //#region Properties
+    
+    private final BooleanProperty isLoading = new SimpleBooleanProperty(this, "isLoading", false);
+    public boolean getIsLoading() { return isLoading.get(); }
```
Comment (DaRealTurtyWurty) [inline railroad-core/src/main/java/dev/railroadide/core/ui/RRButton.java]:
```suggestion
    public boolean getIsLoading() { 
        return isLoading.get(); 
    }
```

File: railroad-core/src/main/java/dev/railroadide/core/ui/RRButton.java [hunk 2]
```diff
@@ -356,30 +359,34 @@ private void updateContent() {
...
-
-        switch (variant) {
-            case PRIMARY -> getStyleClass().add("primary");
-            case SECONDARY -> getStyleClass().add("secondary");
-            case GHOST -> getStyleClass().add("ghost");
-            case DANGER -> getStyleClass().add("danger");
-            case SUCCESS -> getStyleClass().add("success");
-            case WARNING -> getStyleClass().add("warning");
-        }
+        ObservableList<String> styleClass = getStyleClass();
```
Comment (DaRealTurtyWurty) [inline railroad-core/src/main/java/dev/railroadide/core/ui/RRButton.java:344]:
```suggestion
        List<String> styleClass = getStyleClass();
```

File: railroad-core/src/main/java/dev/railroadide/core/ui/RRButton.java [hunk 3]
```diff
@@ -1,14 +1,19 @@
...
-import dev.railroadide.core.utility.ServiceLocator;
+import dev.railroadide.core.ui.localized.LocalizedTextProperty;
+import dev.railroadide.core.ui.styling.ButtonSize;
+import dev.railroadide.core.ui.styling.ButtonVariant;
 import javafx.animation.ScaleTransition;
+import javafx.beans.property.BooleanProperty;
+import javafx.beans.property.ObjectProperty;
+import javafx.beans.property.SimpleBooleanProperty;
+import javafx.beans.property.SimpleObjectProperty;
+import javafx.collections.ObservableList;
```
Comment (DaRealTurtyWurty) [inline railroad-core/src/main/java/dev/railroadide/core/ui/RRButton.java:11]:
```suggestion
import javafx.collections.ObservableList;
import java.util.List;
```

File: railroad-core/src/main/java/dev/railroadide/core/ui/RRCheckBox.java [hunk 4]
```diff
@@ -0,0 +1,220 @@
...
+
+public class RRCheckBox extends CheckBox {
+
+    private FontIcon icon;
+
+    private Node originalGraphic;
+    private FontIcon loadingSpinner;
+
+    private final BooleanProperty isLoading = new SimpleBooleanProperty(this, "isLoading", false);
+    public boolean getIsLoading() { return isLoading.get(); }
```
Comment (DaRealTurtyWurty) [inline railroad-core/src/main/java/dev/railroadide/core/ui/RRCheckBox.java]:
```suggestion
    public boolean getIsLoading() { 
        return isLoading.get(); 
    }
```

File: railroad-core/src/main/java/dev/railroadide/core/ui/RRRadioButton.java [hunk 5]
```diff
@@ -0,0 +1,208 @@
...
+
+    public static final String[] DEFAULT_STYLE_CLASSES = { "rr-radio-button", "radio-button" };
+
+    private FontIcon icon;
+
+    private Node originalGraphic;
+    private FontIcon loadingSpinner;
+
+    private final BooleanProperty isLoading = new SimpleBooleanProperty(this, "isLoading", false);
+    public boolean getIsLoading() { return isLoading.get(); }
```
Comment (DaRealTurtyWurty) [inline railroad-core/src/main/java/dev/railroadide/core/ui/RRRadioButton.java]:
```suggestion
    public boolean getIsLoading() { 
        return isLoading.get(); 
    }
```

File: railroad-core/src/main/java/dev/railroadide/core/ui/RRToggleButton.java [hunk 6]
```diff
@@ -0,0 +1,208 @@
...
+
+	public static final String[] DEFAULT_STYLE_CLASSES = { "rr-button", "rr-toggle-button", "toggle-button" };
+
+    private FontIcon icon;
+
+    private Node originalGraphic;
+    private FontIcon loadingSpinner;
+
+    private final BooleanProperty isLoading = new SimpleBooleanProperty(this, "isLoading", false);
+    public boolean getIsLoading() { return isLoading.get(); }
```
Comment (DaRealTurtyWurty) [inline railroad-core/src/main/java/dev/railroadide/core/ui/RRToggleButton.java]:
```suggestion
    public boolean getIsLoading() { 
        return isLoading.get(); 
    }
```

**Review by DaRealTurtyWurty — CHANGES_REQUESTED** [review]
For the most part, everything looks fine. The only problem I have is the inconsistencies in the changes. some places you've got the `{` on the next line rather than same line, sometimes you've put a space between `Object` and `...` (for `Object... args`). 

I also don't like the `_0` thing. I'm not sure where thats come from, but we use `$` everywhere throughout the project as we're not updated to Java 25 yet, so we can't use a single `_`.

You also are sometimes using `this.` behind method invocations. Typically you may see `this.` used behind fields, but not methods. As for why, I don't know, thats just the standard that seems to be used most often, so try to avoid using `this.` for methods unless specifically required (pretty much never the case).

Another thing to mention is `ITextField` is very C#-esque. We don't use [Hungarian Notation](https://en.wikipedia.org/wiki/Hungarian_notation) in Java, as it is a very old technique that was used before we had IDEs, and serves no modern purpose. Unfortunately, I can't think of a better name for it right now. Maybe just `TextFieldable`, idk its weird, but better than having an `I` prefix.

Also, not a fan of `#region`, which is once again really a C# thing. I think they're just unnecessary, your IDE can collapse any blocks (methods, classes) when you're reading the code anyways, I think hiding an entire section is more likely to cause problems than to actually help solve any.

**Comment by Exanc** [comment]
You wouldn't believe what language I'm using on my job 😂

Also we may need to agree on a single Java formatter cause I'm using VSCode. We could put it in a pre-commit hook or something...

File: railroad-core/src/main/java/dev/railroadide/core/ui/RRButton.java (hunk 2 above)
Comment (Exanc) [reply railroad-core/src/main/java/dev/railroadide/core/ui/RRButton.java:344]: Cannot use List, the `removeAll` method is only part of the `ObservableList` interface and is responsible for sending a change event.

File: railroad-core/src/main/java/dev/railroadide/core/ui/RRButton.java (hunk 3 above)
Comment (Exanc) [reply railroad-core/src/main/java/dev/railroadide/core/ui/RRButton.java:11]: Same here, can't use the `List` interface.

File: railroad-core/src/main/java/dev/railroadide/core/ui/RRButton.java (hunk 2 above)
Comment (DaRealTurtyWurty) [reply railroad-core/src/main/java/dev/railroadide/core/ui/RRButton.java:344]: Huh, missed that lol. Okay that's fine then 👍.

**Comment by DaRealTurtyWurty** [comment]
I'm running into some errors with this PR:
```
Exception in thread "JavaFX Application Thread" java.util.IllegalFormatConversionException: d != com.sun.javafx.collections.ObservableListWrapper
	at java.base/java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4515)
	at java.base/java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:3066)
	at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:3021)
	at java.base/java.util.Formatter.format(Formatter.java:2791)
	at java.base/java.util.Formatter.format(Formatter.java:2728)
	at java.base/java.lang.String.format(String.java:4386)
	at dev.railroadide.railroad.localization.L18n.localize(L18n.java:187)
	at dev.railroadide.railroad.Services$2.get(Services.java:52)
	at dev.railroadide.core.ui.localized.LocalizedTextProperty.updateTranslation(LocalizedTextProperty.java:81)
	at dev.railroadide.core.ui.localized.LocalizedTextProperty.lambda$initialize$1(LocalizedTextProperty.java:61)
	at javafx.base@21.0.2/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:147)
	at javafx.base@21.0.2/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.base@21.0.2/javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:104)
	at javafx.base@21.0.2/javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:111)
	at javafx.base@21.0.2/javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:145)
	at javafx.base@21.0.2/javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:50)
	at dev.railroadide.core.ui.localized.LocalizedTextProperty.setTranslationKey(LocalizedTextProperty.java:122)
	at dev.railroadide.core.ui.localized.LocalizedLabel.setKey(LocalizedLabel.java:40)
	at dev.railroadide.core.ui.localized.LocalizedLabel.<init>(LocalizedLabel.java:24)
	at dev.railroadide.railroad.welcome.WelcomeHeaderPane.<init>(WelcomeHeaderPane.java:28)
	at dev.railroadide.railroad.welcome.WelcomePane.<init>(WelcomePane.java:39)
	at dev.railroadide.railroad.Railroad.start(Railroad.java:165)
	at javafx.graphics@21.0.2/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:839)
	at javafx.graphics@21.0.2/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:483)
	at javafx.graphics@21.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@21.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@21.0.2/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Exception in thread "JavaFX Application Thread" java.util.IllegalFormatConversionException: d != com.sun.javafx.collections.ObservableListWrapper
	at java.base/java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4515)
	at java.base/java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:3066)
	at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:3021)
	at java.base/java.util.Formatter.format(Formatter.java:2791)
	at java.base/java.util.Formatter.format(Formatter.java:2728)
	at java.base/java.lang.String.format(String.java:4386)
	at dev.railroadide.railroad.localization.L18n.localize(L18n.java:187)
	at dev.railroadide.railroad.Services$2.get(Services.java:52)
	at dev.railroadide.core.ui.localized.LocalizedTextProperty.updateTranslation(LocalizedTextProperty.java:81)
	at dev.railroadide.core.ui.localized.LocalizedTextProperty.lambda$initialize$2(LocalizedTextProperty.java:62)
	at javafx.base@21.0.2/com.sun.javafx.binding.ListExpressionHelper$SingleListChange.fireValueChangedEvent(ListExpressionHelper.java:298)
	at javafx.base@21.0.2/com.sun.javafx.binding.ListExpressionHelper.fireValueChangedEvent(ListExpressionHelper.java:107)
	at javafx.base@21.0.2/javafx.beans.property.ListPropertyBase.fireValueChangedEvent(ListPropertyBase.java:203)
	at javafx.base@21.0.2/javafx.beans.property.ListPropertyBase.lambda$new$0(ListPropertyBase.java:57)
	at javafx.base@21.0.2/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:162)
	at javafx.base@21.0.2/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:71)
	at javafx.base@21.0.2/javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:246)
	at javafx.base@21.0.2/javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.base@21.0.2/javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.base@21.0.2/javafx.collections.ObservableListBase.endChange(ObservableListBase.java:210)
	at javafx.base@21.0.2/javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:102)
	at javafx.base@21.0.2/javafx.collections.ObservableListBase.setAll(ObservableListBase.java:264)
	at javafx.base@21.0.2/javafx.beans.binding.ListExpression.setAll(ListExpression.java:337)
	at dev.railroadide.core.ui.localized.LocalizedTextProperty.setTranslationArgs(LocalizedTextProperty.java:130)
	at dev.railroadide.core.ui.localized.LocalizedLabel.setKey(LocalizedLabel.java:39)
	at dev.railroadide.railroad.welcome.WelcomeHeaderPane.updateProjectStats(WelcomeHeaderPane.java:145)
	at dev.railroadide.railroad.welcome.WelcomeHeaderPane.initializeProjectStats(WelcomeHeaderPane.java:139)
	at dev.railroadide.railroad.welcome.WelcomeHeaderPane.<init>(WelcomeHeaderPane.java:51)
	at dev.railroadide.railroad.welcome.WelcomePane.<init>(WelcomePane.java:39)
	at dev.railroadide.railroad.Railroad.start(Railroad.java:165)
	at javafx.graphics@21.0.2/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:839)
	at javafx.graphics@21.0.2/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:483)
	at javafx.graphics@21.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@21.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@21.0.2/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by DaRealTurtyWurty** [comment]
Also here:
```
Exception in thread "JavaFX Application Thread" java.util.IllegalFormatConversionException: d != com.sun.javafx.collections.ObservableListWrapper
	at java.base/java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4515)
	at java.base/java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:3066)
	at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:3021)
	at java.base/java.util.Formatter.format(Formatter.java:2791)
	at java.base/java.util.Formatter.format(Formatter.java:2728)
	at java.base/java.lang.String.format(String.java:4386)
	at dev.railroadide.railroad.localization.L18n.localize(L18n.java:187)
	at dev.railroadide.railroad.Services$2.get(Services.java:52)
	at dev.railroadide.core.ui.localized.LocalizedTextProperty.updateTranslation(LocalizedTextProperty.java:81)
	at dev.railroadide.core.ui.localized.LocalizedTextProperty.lambda$initialize$1(LocalizedTextProperty.java:61)
	at javafx.base@21.0.2/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:147)
	at javafx.base@21.0.2/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.base@21.0.2/javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:104)
	at javafx.base@21.0.2/javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:111)
	at javafx.base@21.0.2/javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:145)
	at javafx.base@21.0.2/javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:50)
	at dev.railroadide.core.ui.localized.LocalizedTextProperty.setTranslationKey(LocalizedTextProperty.java:122)
	at dev.railroadide.core.ui.localized.LocalizedLabel.setKey(LocalizedLabel.java:40)
	at dev.railroadide.core.ui.localized.LocalizedLabel.<init>(LocalizedLabel.java:24)
	at dev.railroadide.railroad.settings.ui.DetectedJdkListPane.<init>(DetectedJdkListPane.java:40)
	at dev.railroadide.railroad.settings.ui.SettingsPane.lambda$new$0(SettingsPane.java:137)
	at javafx.base@21.0.2/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:192)
	at javafx.base@21.0.2/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.base@21.0.2/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:80)
	at javafx.base@21.0.2/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.base@21.0.2/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.base@21.0.2/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at javafx.controls@21.0.2/javafx.scene.control.SelectionModel.setSelectedItem(SelectionModel.java:105)
	at javafx.controls@21.0.2/javafx.scene.control.MultipleSelectionModelBase.lambda$new$0(MultipleSelectionModelBase.java:67)
	at javafx.base@21.0.2/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:147)
	at javafx.base@21.0.2/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.base@21.0.2/javafx.beans.property.ReadOnlyIntegerPropertyBase.fireValueChangedEvent(ReadOnlyIntegerPropertyBase.java:78)
	at javafx.base@21.0.2/javafx.beans.property.ReadOnlyIntegerWrapper.fireValueChangedEvent(ReadOnlyIntegerWrapper.java:102)
	at javafx.base@21.0.2/javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:114)
	at javafx.base@21.0.2/javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148)
	at javafx.controls@21.0.2/javafx.scene.control.SelectionModel.setSelectedIndex(SelectionModel.java:69)
	at javafx.controls@21.0.2/javafx.scene.control.MultipleSelectionModelBase.select(MultipleSelectionModelBase.java:424)
	at javafx.controls@21.0.2/javafx.scene.control.TreeView$TreeViewBitSetSelectionModel.select(TreeView.java:1589)
	at javafx.controls@21.0.2/javafx.scene.control.TreeView$TreeViewBitSetSelectionModel.select(TreeView.java:1332)
	at dev.railroadide.railroad.settings.ui.SettingsPane.<init>(SettingsPane.java:210)
	at dev.railroadide.railroad.settings.ui.SettingsPane.lambda$openSettingsWindow$4(SettingsPane.java:224)
	at javafx.graphics@21.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@21.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@21.0.2/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by DaRealTurtyWurty** [comment]
And all of these:
```
Dec 09, 2025 10:15:36 AM javafx.scene.control.cell.PropertyValueFactory getCellDataReflectively
WARNING: Can not retrieve property 'name' in PropertyValueFactory: javafx.scene.control.cell.PropertyValueFactory@16c388e5 with provided class type: class dev.railroadide.railroad.theme.ui.ThemeExamplePane$ProjectData
java.lang.IllegalStateException: Cannot read from unreadable property name
	at javafx.base@21.0.2/com.sun.javafx.property.PropertyReference.get(PropertyReference.java:167)
	at javafx.controls@21.0.2/javafx.scene.control.cell.PropertyValueFactory.getCellDataReflectively(PropertyValueFactory.java:183)
	at javafx.controls@21.0.2/javafx.scene.control.cell.PropertyValueFactory.call(PropertyValueFactory.java:153)
	at javafx.controls@21.0.2/javafx.scene.control.cell.PropertyValueFactory.call(PropertyValueFactory.java:132)
	at javafx.controls@21.0.2/javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:592)
	at javafx.controls@21.0.2/javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:577)
	at javafx.controls@21.0.2/javafx.scene.control.TableCell.updateItem(TableCell.java:681)
	at javafx.controls@21.0.2/javafx.scene.control.TableCell.indexChanged(TableCell.java:485)
	at javafx.controls@21.0.2/javafx.scene.control.IndexedCell$1.invalidated(IndexedCell.java:85)
	at javafx.base@21.0.2/javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
	at javafx.base@21.0.2/javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148)
	at javafx.controls@21.0.2/javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:130)
	at javafx.controls@21.0.2/javafx.scene.control.skin.TableRowSkinBase.updateCells(TableRowSkinBase.java:525)
	at javafx.controls@21.0.2/javafx.scene.control.skin.TableRowSkinBase.<init>(TableRowSkinBase.java:155)
	at javafx.controls@21.0.2/javafx.scene.control.skin.TableRowSkin.<init>(TableRowSkin.java:81)
	at javafx.controls@21.0.2/javafx.scene.control.TableRow.createDefaultSkin(TableRow.java:213)
	at javafx.controls@21.0.2/javafx.scene.control.Control.doProcessCSS(Control.java:910)
	at javafx.controls@21.0.2/javafx.scene.control.Control$1.doProcessCSS(Control.java:88)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:68)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Node.processCSS(Node.java:9555)
	at javafx.graphics@21.0.2/javafx.scene.Node.applyCss(Node.java:9642)
	at javafx.controls@21.0.2/javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1820)
	at javafx.controls@21.0.2/javafx.scene.control.skin.VirtualFlow.getCell(VirtualFlow.java:1797)
	at javafx.controls@21.0.2/javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(VirtualFlow.java:3069)
	at javafx.controls@21.0.2/javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(VirtualFlow.java:3041)
	at javafx.controls@21.0.2/javafx.scene.control.skin.VirtualFlow$5.invalidated(VirtualFlow.java:865)
	at javafx.base@21.0.2/javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
	at javafx.base@21.0.2/javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148)
	at javafx.controls@21.0.2/javafx.scene.control.skin.VirtualFlow.setCellCount(VirtualFlow.java:912)
	at javafx.controls@21.0.2/javafx.scene.control.skin.TableViewSkinBase.updateItemCount(TableViewSkinBase.java:580)
	at javafx.controls@21.0.2/javafx.scene.control.skin.TableViewSkin.<init>(TableViewSkin.java:123)
	at javafx.controls@21.0.2/javafx.scene.control.TableView.createDefaultSkin(TableView.java:1671)
	at javafx.controls@21.0.2/javafx.scene.control.Control.doProcessCSS(Control.java:910)
	at javafx.controls@21.0.2/javafx.scene.control.Control$1.doProcessCSS(Control.java:88)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:68)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
	at javafx.controls@21.0.2/javafx.scene.control.Control.doProcessCSS(Control.java:913)
	at javafx.controls@21.0.2/javafx.scene.control.Control$1.doProcessCSS(Control.java:88)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:68)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Node.processCSS(Node.java:9555)
	at javafx.graphics@21.0.2/javafx.scene.Scene.doCSSPass(Scene.java:587)
	at javafx.graphics@21.0.2/javafx.scene.Scene.preferredSize(Scene.java:1786)
	at javafx.graphics@21.0.2/javafx.scene.Scene$2.preferredSize(Scene.java:411)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:65)
	at javafx.graphics@21.0.2/javafx.stage.Window$12.invalidated(Window.java:1163)
	at javafx.base@21.0.2/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.base@21.0.2/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.graphics@21.0.2/javafx.stage.Window.setShowing(Window.java:1239)
	at javafx.graphics@21.0.2/javafx.stage.Window.show(Window.java:1254)
	at javafx.graphics@21.0.2/javafx.stage.Stage.show(Stage.java:277)
	at dev.railroadide.railroad.window.WindowBuilder.build(WindowBuilder.java:267)
	at dev.railroadide.railroad.theme.ui.ThemeExamplePane.<init>(ThemeExamplePane.java:57)
	at dev.railroadide.railroad.theme.ui.ThemeSelector.previewSelectedTheme(ThemeSelector.java:106)
	at dev.railroadide.railroad.theme.ui.ThemeSelector.lambda$createContentSection$0(ThemeSelector.java:62)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base@21.0.2/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@21.0.2/javafx.scene.Node.fireEvent(Node.java:8875)
	at javafx.controls@21.0.2/javafx.scene.control.Button.fire(Button.java:203)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:207)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@21.0.2/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@21.0.2/javafx.scene.Scene$MouseHandler.process(Scene.java:3984)
	at javafx.graphics@21.0.2/javafx.scene.Scene.processMouseEvent(Scene.java:1890)
	at javafx.graphics@21.0.2/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2708)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at javafx.graphics@21.0.2/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at javafx.graphics@21.0.2/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
	at java.base/java.lang.Thread.run(Thread.java:1583)

Dec 09, 2025 10:15:36 AM javafx.scene.control.cell.PropertyValueFactory getCellDataReflectively
WARNING: Can not retrieve property 'type' in PropertyValueFactory: javafx.scene.control.cell.PropertyValueFactory@79e2acce with provided class type: class dev.railroadide.railroad.theme.ui.ThemeExamplePane$ProjectData
java.lang.IllegalStateException: Cannot read from unreadable property type
	at javafx.base@21.0.2/com.sun.javafx.property.PropertyReference.get(PropertyReference.java:167)
	at javafx.controls@21.0.2/javafx.scene.control.cell.PropertyValueFactory.getCellDataReflectively(PropertyValueFactory.java:183)
	at javafx.controls@21.0.2/javafx.scene.control.cell.PropertyValueFactory.call(PropertyValueFactory.java:153)
	at javafx.controls@21.0.2/javafx.scene.control.cell.PropertyValueFactory.call(PropertyValueFactory.java:132)
	at javafx.controls@21.0.2/javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:592)
	at javafx.controls@21.0.2/javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:577)
	at javafx.controls@21.0.2/javafx.scene.control.TableCell.updateItem(TableCell.java:681)
	at javafx.controls@21.0.2/javafx.scene.control.TableCell.indexChanged(TableCell.java:485)
	at javafx.controls@21.0.2/javafx.scene.control.IndexedCell$1.invalidated(IndexedCell.java:85)
	at javafx.base@21.0.2/javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
	at javafx.base@21.0.2/javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148)
	at javafx.controls@21.0.2/javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:130)
	at javafx.controls@21.0.2/javafx.scene.control.skin.TableRowSkinBase.updateCells(TableRowSkinBase.java:525)
	at javafx.controls@21.0.2/javafx.scene.control.skin.TableRowSkinBase.<init>(TableRowSkinBase.java:155)
	at javafx.controls@21.0.2/javafx.scene.control.skin.TableRowSkin.<init>(TableRowSkin.java:81)
	at javafx.controls@21.0.2/javafx.scene.control.TableRow.createDefaultSkin(TableRow.java:213)
	at javafx.controls@21.0.2/javafx.scene.control.Control.doProcessCSS(Control.java:910)
	at javafx.controls@21.0.2/javafx.scene.control.Control$1.doProcessCSS(Control.java:88)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:68)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Node.processCSS(Node.java:9555)
	at javafx.graphics@21.0.2/javafx.scene.Node.applyCss(Node.java:9642)
	at javafx.controls@21.0.2/javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1820)
	at javafx.controls@21.0.2/javafx.scene.control.skin.VirtualFlow.getCell(VirtualFlow.java:1797)
	at javafx.controls@21.0.2/javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(VirtualFlow.java:3069)
	at javafx.controls@21.0.2/javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(VirtualFlow.java:3041)
	at javafx.controls@21.0.2/javafx.scene.control.skin.VirtualFlow$5.invalidated(VirtualFlow.java:865)
	at javafx.base@21.0.2/javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
	at javafx.base@21.0.2/javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148)
	at javafx.controls@21.0.2/javafx.scene.control.skin.VirtualFlow.setCellCount(VirtualFlow.java:912)
	at javafx.controls@21.0.2/javafx.scene.control.skin.TableViewSkinBase.updateItemCount(TableViewSkinBase.java:580)
	at javafx.controls@21.0.2/javafx.scene.control.skin.TableViewSkin.<init>(TableViewSkin.java:123)
	at javafx.controls@21.0.2/javafx.scene.control.TableView.createDefaultSkin(TableView.java:1671)
	at javafx.controls@21.0.2/javafx.scene.control.Control.doProcessCSS(Control.java:910)
	at javafx.controls@21.0.2/javafx.scene.control.Control$1.doProcessCSS(Control.java:88)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:68)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
	at javafx.controls@21.0.2/javafx.scene.control.Control.doProcessCSS(Control.java:913)
	at javafx.controls@21.0.2/javafx.scene.control.Control$1.doProcessCSS(Control.java:88)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:68)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Node.processCSS(Node.java:9555)
	at javafx.graphics@21.0.2/javafx.scene.Scene.doCSSPass(Scene.java:587)
	at javafx.graphics@21.0.2/javafx.scene.Scene.preferredSize(Scene.java:1786)
	at javafx.graphics@21.0.2/javafx.scene.Scene$2.preferredSize(Scene.java:411)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:65)
	at javafx.graphics@21.0.2/javafx.stage.Window$12.invalidated(Window.java:1163)
	at javafx.base@21.0.2/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.base@21.0.2/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.graphics@21.0.2/javafx.stage.Window.setShowing(Window.java:1239)
	at javafx.graphics@21.0.2/javafx.stage.Window.show(Window.java:1254)
	at javafx.graphics@21.0.2/javafx.stage.Stage.show(Stage.java:277)
	at dev.railroadide.railroad.window.WindowBuilder.build(WindowBuilder.java:267)
	at dev.railroadide.railroad.theme.ui.ThemeExamplePane.<init>(ThemeExamplePane.java:57)
	at dev.railroadide.railroad.theme.ui.ThemeSelector.previewSelectedTheme(ThemeSelector.java:106)
	at dev.railroadide.railroad.theme.ui.ThemeSelector.lambda$createContentSection$0(ThemeSelector.java:62)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base@21.0.2/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@21.0.2/javafx.scene.Node.fireEvent(Node.java:8875)
	at javafx.controls@21.0.2/javafx.scene.control.Button.fire(Button.java:203)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:207)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@21.0.2/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@21.0.2/javafx.scene.Scene$MouseHandler.process(Scene.java:3984)
	at javafx.graphics@21.0.2/javafx.scene.Scene.processMouseEvent(Scene.java:1890)
	at javafx.graphics@21.0.2/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2708)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at javafx.graphics@21.0.2/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at javafx.graphics@21.0.2/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
	at java.base/java.lang.Thread.run(Thread.java:1583)

Dec 09, 2025 10:15:36 AM javafx.scene.control.cell.PropertyValueFactory getCellDataReflectively
WARNING: Can not retrieve property 'status' in PropertyValueFactory: javafx.scene.control.cell.PropertyValueFactory@265d31c1 with provided class type: class dev.railroadide.railroad.theme.ui.ThemeExamplePane$ProjectData
java.lang.IllegalStateException: Cannot read from unreadable property status
	at javafx.base@21.0.2/com.sun.javafx.property.PropertyReference.get(PropertyReference.java:167)
	at javafx.controls@21.0.2/javafx.scene.control.cell.PropertyValueFactory.getCellDataReflectively(PropertyValueFactory.java:183)
	at javafx.controls@21.0.2/javafx.scene.control.cell.PropertyValueFactory.call(PropertyValueFactory.java:153)
	at javafx.controls@21.0.2/javafx.scene.control.cell.PropertyValueFactory.call(PropertyValueFactory.java:132)
	at javafx.controls@21.0.2/javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:592)
	at javafx.controls@21.0.2/javafx.scene.control.TableColumn.getCellObservableValue(TableColumn.java:577)
	at javafx.controls@21.0.2/javafx.scene.control.TableCell.updateItem(TableCell.java:681)
	at javafx.controls@21.0.2/javafx.scene.control.TableCell.indexChanged(TableCell.java:485)
	at javafx.controls@21.0.2/javafx.scene.control.IndexedCell$1.invalidated(IndexedCell.java:85)
	at javafx.base@21.0.2/javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
	at javafx.base@21.0.2/javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148)
	at javafx.controls@21.0.2/javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:130)
	at javafx.controls@21.0.2/javafx.scene.control.skin.TableRowSkinBase.updateCells(TableRowSkinBase.java:525)
	at javafx.controls@21.0.2/javafx.scene.control.skin.TableRowSkinBase.<init>(TableRowSkinBase.java:155)
	at javafx.controls@21.0.2/javafx.scene.control.skin.TableRowSkin.<init>(TableRowSkin.java:81)
	at javafx.controls@21.0.2/javafx.scene.control.TableRow.createDefaultSkin(TableRow.java:213)
	at javafx.controls@21.0.2/javafx.scene.control.Control.doProcessCSS(Control.java:910)
	at javafx.controls@21.0.2/javafx.scene.control.Control$1.doProcessCSS(Control.java:88)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:68)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Node.processCSS(Node.java:9555)
	at javafx.graphics@21.0.2/javafx.scene.Node.applyCss(Node.java:9642)
	at javafx.controls@21.0.2/javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1820)
	at javafx.controls@21.0.2/javafx.scene.control.skin.VirtualFlow.getCell(VirtualFlow.java:1797)
	at javafx.controls@21.0.2/javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(VirtualFlow.java:3069)
	at javafx.controls@21.0.2/javafx.scene.control.skin.VirtualFlow.getOrCreateCellSize(VirtualFlow.java:3041)
	at javafx.controls@21.0.2/javafx.scene.control.skin.VirtualFlow$5.invalidated(VirtualFlow.java:865)
	at javafx.base@21.0.2/javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113)
	at javafx.base@21.0.2/javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148)
	at javafx.controls@21.0.2/javafx.scene.control.skin.VirtualFlow.setCellCount(VirtualFlow.java:912)
	at javafx.controls@21.0.2/javafx.scene.control.skin.TableViewSkinBase.updateItemCount(TableViewSkinBase.java:580)
	at javafx.controls@21.0.2/javafx.scene.control.skin.TableViewSkin.<init>(TableViewSkin.java:123)
	at javafx.controls@21.0.2/javafx.scene.control.TableView.createDefaultSkin(TableView.java:1671)
	at javafx.controls@21.0.2/javafx.scene.control.Control.doProcessCSS(Control.java:910)
	at javafx.controls@21.0.2/javafx.scene.control.Control$1.doProcessCSS(Control.java:88)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:68)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Parent.doProcessCSS(Parent.java:1401)
	at javafx.graphics@21.0.2/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
	at javafx.controls@21.0.2/javafx.scene.control.Control.doProcessCSS(Control.java:913)
	at javafx.controls@21.0.2/javafx.scene.control.Control$1.doProcessCSS(Control.java:88)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:68)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:147)
	at javafx.graphics@21.0.2/javafx.scene.Node.processCSS(Node.java:9555)
	at javafx.graphics@21.0.2/javafx.scene.Scene.doCSSPass(Scene.java:587)
	at javafx.graphics@21.0.2/javafx.scene.Scene.preferredSize(Scene.java:1786)
	at javafx.graphics@21.0.2/javafx.scene.Scene$2.preferredSize(Scene.java:411)
	at javafx.graphics@21.0.2/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:65)
	at javafx.graphics@21.0.2/javafx.stage.Window$12.invalidated(Window.java:1163)
	at javafx.base@21.0.2/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.base@21.0.2/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.graphics@21.0.2/javafx.stage.Window.setShowing(Window.java:1239)
	at javafx.graphics@21.0.2/javafx.stage.Window.show(Window.java:1254)
	at javafx.graphics@21.0.2/javafx.stage.Stage.show(Stage.java:277)
	at dev.railroadide.railroad.window.WindowBuilder.build(WindowBuilder.java:267)
	at dev.railroadide.railroad.theme.ui.ThemeExamplePane.<init>(ThemeExamplePane.java:57)
	at dev.railroadide.railroad.theme.ui.ThemeSelector.previewSelectedTheme(ThemeSelector.java:106)
	at dev.railroadide.railroad.theme.ui.ThemeSelector.lambda$createContentSection$0(ThemeSelector.java:62)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base@21.0.2/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@21.0.2/javafx.scene.Node.fireEvent(Node.java:8875)
	at javafx.controls@21.0.2/javafx.scene.control.Button.fire(Button.java:203)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:207)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@21.0.2/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@21.0.2/javafx.scene.Scene$MouseHandler.process(Scene.java:3984)
	at javafx.graphics@21.0.2/javafx.scene.Scene.processMouseEvent(Scene.java:1890)
	at javafx.graphics@21.0.2/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2708)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at javafx.graphics@21.0.2/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at javafx.graphics@21.0.2/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
	at java.base/java.lang.Thread.run(Thread.java:1583)

Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: Stage already visible
	at javafx.graphics@21.0.2/javafx.stage.Stage.showAndWait(Stage.java:455)
	at dev.railroadide.railroad.window.WindowBuilder.build(WindowBuilder.java:277)
	at dev.railroadide.railroad.theme.ui.ThemeExamplePane.<init>(ThemeExamplePane.java:57)
	at dev.railroadide.railroad.theme.ui.ThemeSelector.previewSelectedTheme(ThemeSelector.java:106)
	at dev.railroadide.railroad.theme.ui.ThemeSelector.lambda$createContentSection$0(ThemeSelector.java:62)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base@21.0.2/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@21.0.2/javafx.scene.Node.fireEvent(Node.java:8875)
	at javafx.controls@21.0.2/javafx.scene.control.Button.fire(Button.java:203)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:207)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@21.0.2/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@21.0.2/javafx.scene.Scene$MouseHandler.process(Scene.java:3984)
	at javafx.graphics@21.0.2/javafx.scene.Scene.processMouseEvent(Scene.java:1890)
	at javafx.graphics@21.0.2/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2708)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at javafx.graphics@21.0.2/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at javafx.graphics@21.0.2/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by DaRealTurtyWurty** [comment]
The close preview button for the theme preview pane also does not work. It throws an exception saying that the stage is null?

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Cannot invoke "javafx.stage.Stage.close()" because "this.stage" is null
	at dev.railroadide.railroad.theme.ui.ThemeExamplePane.lambda$createFooterSection$2(ThemeExamplePane.java:275)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base@21.0.2/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@21.0.2/javafx.scene.Node.fireEvent(Node.java:8875)
	at javafx.controls@21.0.2/javafx.scene.control.Button.fire(Button.java:203)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:207)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@21.0.2/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@21.0.2/javafx.scene.Scene$MouseHandler.process(Scene.java:3984)
	at javafx.graphics@21.0.2/javafx.scene.Scene.processMouseEvent(Scene.java:1890)
	at javafx.graphics@21.0.2/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2708)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at javafx.graphics@21.0.2/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at javafx.graphics@21.0.2/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by DaRealTurtyWurty** [comment]
Also another one as from before with the translations. Any place where an arg is passed seems to be throwing an exception (if I understand correctly)

```
Exception in thread "JavaFX Application Thread" java.util.IllegalFormatConversionException: d != com.sun.javafx.collections.ObservableListWrapper
	at java.base/java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4515)
	at java.base/java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:3066)
	at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:3021)
	at java.base/java.util.Formatter.format(Formatter.java:2791)
	at java.base/java.util.Formatter.format(Formatter.java:2728)
	at java.base/java.lang.String.format(String.java:4386)
	at dev.railroadide.railroad.localization.L18n.localize(L18n.java:187)
	at dev.railroadide.railroad.Services$2.get(Services.java:52)
	at dev.railroadide.core.ui.localized.LocalizedTextProperty.updateTranslation(LocalizedTextProperty.java:81)
	at dev.railroadide.core.ui.localized.LocalizedTextProperty.lambda$initialize$1(LocalizedTextProperty.java:61)
	at javafx.base@21.0.2/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:147)
	at javafx.base@21.0.2/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.base@21.0.2/javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:104)
	at javafx.base@21.0.2/javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:111)
	at javafx.base@21.0.2/javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:145)
	at javafx.base@21.0.2/javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:50)
	at dev.railroadide.core.ui.localized.LocalizedTextProperty.setTranslationKey(LocalizedTextProperty.java:122)
	at dev.railroadide.core.ui.localized.LocalizedLabel.setKey(LocalizedLabel.java:40)
	at dev.railroadide.railroad.theme.ui.ThemeDownloadPane.lambda$loadThemes$3(ThemeDownloadPane.java:131)
	at javafx.graphics@21.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@21.0.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@21.0.2/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by DaRealTurtyWurty** [comment]
Also worth noting that the "Loading themes..." text does not go away. It stays even once the themes are loaded.
image

**Comment by DaRealTurtyWurty** [comment]
And the same issue with closing the stage also occurs here in the download pane too.
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Cannot invoke "javafx.stage.Stage.close()" because "this.stage" is null
	at dev.railroadide.railroad.theme.ui.ThemeDownloadPane.lambda$createFooterSection$2(ThemeDownloadPane.java:110)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base@21.0.2/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@21.0.2/javafx.scene.Node.fireEvent(Node.java:8875)
	at javafx.controls@21.0.2/javafx.scene.control.Button.fire(Button.java:203)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:207)
	at javafx.controls@21.0.2/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at javafx.base@21.0.2/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at javafx.base@21.0.2/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@21.0.2/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@21.0.2/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@21.0.2/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@21.0.2/javafx.scene.Scene$MouseHandler.process(Scene.java:3984)
	at javafx.graphics@21.0.2/javafx.scene.Scene.processMouseEvent(Scene.java:1890)
	at javafx.graphics@21.0.2/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2708)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics@21.0.2/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at javafx.graphics@21.0.2/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at javafx.graphics@21.0.2/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@21.0.2/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Exanc** [comment]
I know exactly were this comes from but DAAMM!

**Comment by Exanc** [comment]
This should fix every error you encountered, and I also fixed some extra details.

Note that I deleted the `showAndWait()` cause it's not possible to use it with the current code base.
I you want to keep it (i don't see why it would be useful but ok) you wouldn't be able to use `MacUtils` with modals or make it work with a stage that is not shown yet.

File: railroad-core/src/main/java/dev/railroadide/core/ui/domain/TextFieldControl.java [hunk 7]
```diff
@@ -0,0 +1,69 @@
...
+     * Set the text field as disabled state
+     * @param disabled
+     */
+    void setDisabledState(boolean disabled);
+
+    /**
+     * 
+     * @param placeholder
+     */
+    void setPlaceholder(String placeholder);
```
Comment (DaRealTurtyWurty) [inline railroad-core/src/main/java/dev/railroadide/core/ui/domain/TextFieldControl.java:56]: Probably should say what this method does, just like all the others do

File: src/main/java/dev/railroadide/railroad/theme/ui/ThemeDownloadPane.java [hunk 8]
```diff
@@ -103,8 +106,12 @@ private HBox createFooterSection() {
         footerSection.setPadding(new Insets(16, 0, 0, 0));
 
         var closeButton = new RRButton("railroad.generic.close");
-        closeButton.setVariant(RRButton.ButtonVariant.SECONDARY);
-        closeButton.setOnAction($ -> stage.close());
+        closeButton.setVariant(ButtonVariant.SECONDARY);
+        closeButton.setOnAction(e -> {
+            var target = (javafx.scene.Node) e.getTarget();
+            var stage = (javafx.stage.Stage) target.sceneProperty().get().getWindow();
```
Comment (DaRealTurtyWurty) [inline src/main/java/dev/railroadide/railroad/theme/ui/ThemeDownloadPane.java]: These should be imported.

File: src/main/java/dev/railroadide/railroad/theme/ui/ThemeExamplePane.java [hunk 9]
```diff
@@ -251,15 +272,24 @@ private HBox createFooterSection() {
         footer.setPadding(new Insets(16, 0, 0, 0));
 
         var closeButton = new RRButton("railroad.home.settings.appearance.preview.close");
-        closeButton.setVariant(RRButton.ButtonVariant.SECONDARY);
-        closeButton.setOnAction(e -> stage.close());
+        closeButton.setVariant(ButtonVariant.SECONDARY);
+        closeButton.setOnAction(e -> {
+            var target = (javafx.scene.Node) e.getTarget();
+            var stage = (javafx.stage.Stage) target.sceneProperty().get().getWindow();
```
Comment (DaRealTurtyWurty) [inline src/main/java/dev/railroadide/railroad/theme/ui/ThemeExamplePane.java]: These should be imported

File: src/main/java/dev/railroadide/railroad/theme/ui/ThemeExamplePane.java [hunk 10]
```diff
@@ -251,15 +272,24 @@ private HBox createFooterSection() {
...
         var applyButton = new RRButton("railroad.home.settings.appearance.preview.apply");
-        applyButton.setVariant(RRButton.ButtonVariant.PRIMARY);
-        applyButton.setOnAction($ -> {
+        applyButton.setVariant(ButtonVariant.PRIMARY);
+        applyButton.setOnAction(e -> {
             // Apply the theme to the main application
             ThemeManager.setTheme(themeName.replace(".css", ""));
+            
+            var target = (javafx.scene.Node) e.getTarget();
+            var stage = (javafx.stage.Stage) target.sceneProperty().get().getWindow();
```
Comment (DaRealTurtyWurty) [inline src/main/java/dev/railroadide/railroad/theme/ui/ThemeExamplePane.java]: These should be imported

**Review by DaRealTurtyWurty — CHANGES_REQUESTED** [review]

**Review by Exanc — COMMENTED** [review]
Here you go :)

**Review by DaRealTurtyWurty — APPROVED** [review]
